#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.whm.peppa.web.db.dao.model
  mapperLocations: classpath:tables/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://192.168.1.13:3306/peppa?useUnicode=true&characterEncoding=GBK
    username: aaa
    password: aaa
    driver-class-name: com.mysql.cj.jdbc.Driver